conky.config = {
    alignment = 'top_right',
    background = false,
    update_interval = 60,
    double_buffer = true,
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    font = 'Zhi Mang Xing:size=120'
};

conky.text = [[
${exec lunis now -l zh -f "{y-s}{y-b}年 {m-S} {d-s}{d-b}日"}
]];
