[options]
HoldPkg     = pacman glibc
Architecture = auto

Color
CheckSpace
VerbosePkgLists
ILoveCandy
UseSyslog
ParallelDownloads = 8

IgnorePkg = nordvpn-bin other-package

SigLevel = Required DatabaseRequired
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

