# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME

window_padding_width 4

remember_window_size yes
initial_window_width 640
initial_window_height 400

export TERM=xterm-256colorMon Monste

enabled_layouts tall:bias=50;full_size=1;mirrored=false
fullscreen yes

map f11 toggle_fullscreen
map ctrl+backspace send_text all \x17

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3

font_size 12.0

# Added by Gogh
include colors.conf
