# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  link:
    desc: Create symbolic links from repo to actually config location
    cmds:
      - chmod +x ./scripts/link.sh
      - ./scripts/link.sh
