# https://taskfile.dev

version: "3"

vars:
  WALLPAPER: /home/accodius/Downloads/wallhaven-6d6xwl.jpg

tasks:
  install-fonts:
    cmds:
      - cp ./ZhiMangXing-Regular.ttf ~/.local/share/fonts/

  install-hypr:
    cmds:
      - for:
          - hyprland
          - hyprpaper
          - hyprshot
          - swaync
          - rofi
          - pavucontrol
          - waybar
          - wev
          - uwsm
          - eww
        cmd: echo "implement this"

  link-wallpaper:
    internal: true
    cmds:
      - for:
          - config/rofi
        cmd: ln -sf {{.WALLPAPER}} "$(realpath {{.ITEM}})/.current_wallpaper"

  link-file:
    internal: true
    cmds:
      - for:
          - .gitconfig
          - .p10k.zsh
          - .zshrc
        cmd: ln -sf "$(realpath {{.ITEM}})" "$(realpath ~)/{{.ITEM}}"

  link-config-d:
    internal: true
    cmds:
      - for:
          - fastfetch
          - hypr
          - waybar
          - wezterm
          - nvim
          - kitty
          - yazi
          - swaync
          - rofi
          - wofi
          - matugen
          - eww
        cmd: |
          rm -rf "$(realpath ~)/.config/{{.ITEM}}"
          ln -sf "$(realpath config/{{.ITEM}})" "$(realpath ~)/.config/{{.ITEM}}"

  link:
    desc: Create symbolic links from repo to actually config location
    deps:
      - link-file
      - link-config-d
      - link-wallpaper

  allow-x-all:
    desc: Allow all scripts in config to execute
    silent: true
    cmds:
      - echo "The following files will be modified:"
      - find . -type f -name "*.sh"
      - sudo -v
      - read -p "Continue? [y/N] " ans && [ "$ans" = "y" ]
      - sudo find . -type f -name "*.sh" -exec chmod +x {} +
