-- Generated by matugen
-- WezTerm color scheme
-- DO NOT EDIT MANUALLY

return {
	-- Core colors
	foreground = "{{ colors.on_surface.default.hex }}",
	background = "{{ colors.surface.default.hex }}",

	-- Cursor
	cursor_bg = "{{ colors.secondary.default.hex }}",
	cursor_fg = "{{ colors.surface.default.hex }}",
	cursor_border = "{{ colors.secondary.default.hex }}",

	-- Selection
	selection_fg = "{{ colors.on_secondary.default.hex }}",
	selection_bg = "{{ colors.secondary_fixed_dim.default.hex }}",

	-- UI elements
	scrollbar_thumb = "{{ colors.outline.default.hex }}",
	split = "{{ colors.outline_variant.default.hex }}",

	-- ANSI palette (0–7)
	ansi = {
		"{{ colors.surface_dim.default.hex }}", -- black
		"{{ colors.error.default.hex }}", -- red
		"{{ colors.primary.default.hex }}", -- green
		"{{ colors.tertiary.default.hex }}", -- yellow
		"{{ colors.secondary.default.hex }}", -- blue
		"{{ colors.tertiary_container.default.hex }}", -- magenta
		"{{ colors.secondary_container.default.hex }}", -- cyan
		"{{ colors.on_surface.default.hex }}", -- white
	},

	-- Bright ANSI palette (8–15)
	brights = {
		"{{ colors.surface_bright.default.hex }}", -- bright black
		"{{ colors.error_container.default.hex }}", -- bright red
		"{{ colors.primary_container.default.hex }}", -- bright green
		"{{ colors.tertiary_fixed.default.hex }}", -- bright yellow
		"{{ colors.secondary_fixed.default.hex }}", -- bright blue
		"{{ colors.tertiary_fixed_dim.default.hex }}", -- bright magenta
		"{{ colors.secondary_fixed_dim.default.hex }}", -- bright cyan
		"{{ colors.on_surface_variant.default.hex }}", -- bright white
	},

	-- Indexed colors (16–255)
	indexed = {
		[136] = "{{ colors.inverse_primary.default.hex }}",
	},

	-- IME / compose cursor
	compose_cursor = "{{ colors.inverse_primary.default.hex }}",

	-- Copy mode
	copy_mode_active_highlight_bg = { Color = "{{ colors.inverse_surface.default.hex }}" },
	copy_mode_active_highlight_fg = { Color = "{{ colors.inverse_on_surface.default.hex }}" },

	copy_mode_inactive_highlight_bg = { Color = "{{ colors.primary.default.hex }}" },
	copy_mode_inactive_highlight_fg = { Color = "{{ colors.on_primary.default.hex }}" },

	-- Quick select
	quick_select_label_bg = { Color = "{{ colors.tertiary.default.hex }}" },
	quick_select_label_fg = { Color = "{{ colors.on_tertiary.default.hex }}" },

	quick_select_match_bg = { Color = "{{ colors.secondary.default.hex }}" },
	quick_select_match_fg = { Color = "{{ colors.on_secondary.default.hex }}" },

	-- Launcher / input selector (nightly-safe)
	input_selector_label_bg = { Color = "{{ colors.surface_container_high.default.hex }}" },
	input_selector_label_fg = { Color = "{{ colors.on_surface.default.hex }}" },

	launcher_label_bg = { Color = "{{ colors.surface_container_high.default.hex }}" },
	launcher_label_fg = { Color = "{{ colors.on_surface.default.hex }}" },
}
