general {
    immediate_render = true
    transparent = true
    hide_cursor = true
}

background {
    monitor =
    path = $HOME/Pictures/Wallpapers/wallhaven-6d6xwl_3840x2160.png

    blur_passes = 3
    blur_size = 2
    brightness =0.3
}


input-field {
    size = 300, 30
    outline_thickness = 0

    dots_size = 0.25
    dots_spacing = 0.55
    dots_center = true
    dots_rounding = -1

    # outer_color = rgba(0, 0, 0, 0)
    # inner_color =rgb(0, 0, 0, 0)
    # font_color = rgb(200, 200, 200)  

    check_color = rgba(204, 136, 34, 0.8)
    fail_color = rgba(204, 34, 34, 0.8)
    fail_text = "$FAIL ($ATTEMPTS)"

    position = 0, -468
    halign = center
    valign = center
}

label {
  monitor = 
  text = cmd[update:1000] echo "$(~/.config/scripts/song-status.sh)"
  color = rgba(242, 243, 244, 0.75)
  font_size = 16
  font_family = Roboto
  position = 0, -30
  halign = center 
  valign = top
}

label {
    monitor =
    text = cmd[update:10000] /home/accodius/.cargo/bin/lunis now -l vi -f '{y-s} {y-b} - {m-S} - {d-s} {d-b} ngày {d-n}'
    color = rgba(242, 243, 244, 0.75)
    font_size = 16 
    font_family = Lexend
    position = 0, 200
    halign = center
    valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 20
  font_family = Lexend Bold
  position = 0, 405
  halign = center
  valign = center
}

label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%k:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 93
  font_family = Lexend Bold
  position = 0, 310
  halign = center
  valign = center
}

shape {
    monitor =
    size = 30, 30
    color = rgba(0, 0, 0, 0.0) # no fill
    rounding = 1 # circle
    rotate = 45
    border_size = 4
    border_color = rgba(255, 255, 255, 1.0)

    position = 0, 80
    halign = center
    valign = bottom 
}


label {
    monitor =
    text = $USER
    color = rgba(242, 243, 244, 0.8)
    font_size = 16
    font_family = Lexend Bold

    position = 0,30 
    halign = center
    valign = bottom 
}


