source = ~/.config/hypr/lib/monitor.hyprland.conf
source = ~/.config/hypr/lib/env.hyprland.conf
source = ~/.config/hypr/lib/startup.hyprland.conf
source = ~/.config/hypr/lib/ui.hyprland.conf
source = ~/.config/hypr/lib/inputs.hyprland.conf
source = ~/.config/hypr/lib/binds.hyprland.conf
source = ~/.config/hypr/lib/rules.hyprland.conf

xwayland {
  force_zero_scaling = true
}
