-- Generated by matugen
-- WezTerm color scheme
-- DO NOT EDIT MANUALLY

return {
	-- Core colors
	foreground = "#f1dedd",
	background = "#1a1111",

	-- Cursor
	cursor_bg = "#e7bdb9",
	cursor_fg = "#1a1111",
	cursor_border = "#e7bdb9",

	-- Selection
	selection_fg = "#442928",
	selection_bg = "#e7bdb9",

	-- UI elements
	scrollbar_thumb = "#a08c8b",
	split = "#534342",

	-- ANSI palette (0–7)
	ansi = {
		"#1a1111", -- black
		"#ffb4ab", -- red
		"#ffb3ae", -- green
		"#e2c28c", -- yellow
		"#e7bdb9", -- blue
		"#594319", -- magenta
		"#5d3f3d", -- cyan
		"#f1dedd", -- white
	},

	-- Bright ANSI palette (8–15)
	brights = {
		"#423736", -- bright black
		"#93000a", -- bright red
		"#733330", -- bright green
		"#ffdea7", -- bright yellow
		"#ffdad7", -- bright blue
		"#e2c28c", -- bright magenta
		"#e7bdb9", -- bright cyan
		"#d8c2c0", -- bright white
	},

	-- Indexed colors (16–255)
	indexed = {
		[136] = "#904a46",
	},

	-- IME / compose cursor
	compose_cursor = "#904a46",

	-- Copy mode
	copy_mode_active_highlight_bg = { Color = "#f1dedd" },
	copy_mode_active_highlight_fg = { Color = "#382e2d" },

	copy_mode_inactive_highlight_bg = { Color = "#ffb3ae" },
	copy_mode_inactive_highlight_fg = { Color = "#571d1c" },

	-- Quick select
	quick_select_label_bg = { Color = "#e2c28c" },
	quick_select_label_fg = { Color = "#402d04" },

	quick_select_match_bg = { Color = "#e7bdb9" },
	quick_select_match_fg = { Color = "#442928" },

	-- Launcher / input selector (nightly-safe)
	-- input_selector_label_bg = { Color = "#322827" },
	-- input_selector_label_fg = { Color = "#f1dedd" },

	-- launcher_label_bg = { Color = "#322827" },
	-- launcher_label_fg = { Color = "#f1dedd" },
}
