cursor_text_color #f1dedd
cursor #e7bdb9

foreground            #f1dedd
background            #1a1111
selection_foreground  #442928
selection_background  #e7bdb9
scrollbar_handle_color #ffb3ae
url_color             #ffb3ae

#tab
active_tab_foreground   #534342
active_tab_background   #ffb3ae
inactive_tab_foreground #534342
inactive_tab_background #a08c8b
tab_bar_background      #1a1111
