cursor_text_color #dee4de
cursor #b4ccbd

foreground            #dee4de
background            #0f1511
selection_foreground  #20352a
selection_background  #b4ccbd
scrollbar_handle_color #8ed5b0
url_color             #8ed5b0

#tab
active_tab_foreground   #404943
active_tab_background   #8ed5b0
inactive_tab_foreground #404943
inactive_tab_background #8a938c
tab_bar_background      #0f1511
