# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME

window_padding_width 4

remember_window_size no
initial_window_width 640
initial_window_height 400

export TERM=xterm-256colorMon Monste

enabled_layouts tall:bias=50;full_size=1;mirrored=false
fullscreen yes

hide_window_decorations yes
wayland_titlebar_color system

map f11 toggle_fullscreen
map ctrl+backspace send_text all \x17

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3

font_size 12.0

# Added by Gogh
include colors.conf

# ─────────────────────────────────────────────────────────────
#  Font
# ─────────────────────────────────────────────────────────────
font_family              RobotoMono Nerd Font
bold_font                auto
italic_font              auto
bold_italic_font         auto
font_size                12.0

# ─────────────────────────────────────────────────────────────
#  Window and UI
# ─────────────────────────────────────────────────────────────
initial_window_width     80c
initial_window_height    24c
hide_window_decorations  no
draw_minimal_borders     yes
tab_bar_min_tabs         1
tab_bar_style            powerline
tab_powerline_style      slanted
tab_bar_edge             bottom
tab_bar_margin_height    0
tab_bar_margin_width     0
tab_title_template       "{index}: {title}"
tab_max_width            64
show_tab_bar             when_multiple_windows
