gui:
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true
os:
  editPreset: "nvim"
git:
  pagers:
    - pager: delta --paging=never
      colorArg: always
    - externalDiffCommand: difft --color=always --display=side-by-side
