[config.wallpaper]
  command = "awww"
  arguments = ["img", "--transition-type", "center"]
  set = true

[templates.gtk4]
  input_path  = './templates/gtk/colors.css'
  output_path = '~/.config/gtk-4.0/gtk.css'

[templates.gtk3]
  input_path  = './templates/gtk/colors.css'
  output_path = '~/.config/gtk-3.0/gtk.css'

[templates.rofi]
  input_path  = './templates/rofi.rasi'
  output_path = '~/.config/rofi/colors.rasi'

[templates.qtct]
  input_path  = './templates/qtct.conf'
  output_path = '~/.local/share/color-schemes/Matugen.colors'

