# : Manager [[[

[mgr]
  cwd = { fg = "#dee4de" }

  # Tab
  tab_active   = { fg = "#003824", bg = "#8ed5b0", bold = true }
  tab_inactive = { fg = "#aaf2cb", bg = "#002113" }
  tab_width    = 1

  # Find
  find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
  find_position = { fg = "#ffb4ab", bold = true, italic = true }

  # Marker
  marker_copied   = { fg = "#62c8f3", bg = "#62c8f3" }
  marker_cut      = { fg = "#c0e9fa", bg = "#c0e9fa" }
  marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
  marker_selected = { fg = "#a5cdde", bg = "#a5cdde" }

  # Count
  count_copied   = { fg = "#001f29", bg = "#c0e9fa" }
  count_cut      = { fg = "#001f29", bg = "#c0e9fa" }
  count_selected = { fg = "#003824", bg = "#a5cdde" }

  # Border
  border_symbol = "│"
  border_style  = { fg = "#8ed5b0" }

  # : ]]]


  # : Status [[[

[status]
  separator_open  = "🭁"
  separator_close = "🭠"
  separator_style = { bg = "#003824", fg = "#8ed5b0" }

[mode]
  # Mode
  normal_main = { bg = "#8ed5b0", fg = "#003824", bold = true }
  normal_alt  = { bg = "#404943", fg = "#c0c9c1" }

  # Select mode
  select_main = { bg = "#b4ccbd", fg = "#20352a", bold = true }
  select_alt  = { bg = "#404943", fg = "#c0c9c1" }

  # Unset mode
  unset_main = { bg = "#a5cdde", fg = "#063543", bold = true }
  unset_alt  = { bg = "#404943", fg = "#c0c9c1" }

  # Progress
  progress_label  = { bold = true }
  progress_normal = { fg = "#8ed5b0", bg = "#353b36" }
  progress_error  = { fg = "#ffb4ab", bg = "#353b36" }

  # Permissions
  permissions_t = { fg = "#5e8a6e" }
  permissions_w = { fg = "#3f8bab" }
  permissions_x = { fg = "#ff2b12" }
  permissions_r = { fg = "#32b8ef" }
  permissions_s = { fg = "#25de7a" }

  # : ]]]


  # : Select [[[

[select]
  border   = { fg = "#8ed5b0" }
  active   = { fg = "#a5cdde", bold = true }
  inactive = {}

  # : ]]]


  # : Input [[[

[input]
  border = { fg = "#8ed5b0" }
  value  = { fg = "#dee4de" }

  # : ]]]


  # : Completion [[[

[completion]
  border = { fg = "#8ed5b0", bg = "#003824" }

  # : ]]]


  # : Tasks [[[

[tasks]
  border  = { fg = "#8ed5b0" }
  title   = {}
  hovered = { fg = "#c0e9fa", underline = true }

  # : ]]]


  # : Which [[[

[which]
  cols            = 3
  mask            = { bg = "#353b36" }
  cand            = { fg = "#8ed5b0" }
  rest            = { fg = "#003824" }
  desc            = { fg = "#dee4de" }
  separator       = " ▶ "
  separator_style = { fg = "#dee4de" }

  # : ]]]


  # : Help [[[

[help]
  on     = { fg = "#dee4de" }
  run    = { fg = "#dee4de" }
  footer = { fg = "#20352a", bg = "#b4ccbd" }

  # : ]]]


  # : Notify [[[

[notify]
  title_info  = { fg = "#a5cdde" }
  title_warn  = { fg = "#8ed5b0" }
  title_error = { fg = "#ffb4ab" }

  # : ]]]


  # : File-specific styles [[[

[filetype]
  rules = [
    # Images
    { mime = "image/*", fg = "#b4ccbd" },

    # Videos
    { mime = "video/*", fg = "#a5cdde" },
    { mime = "audio/*", fg = "#a5cdde" },

    # Archives
    { mime = "application/zip", fg = "#ffb4ab" },
    { mime = "application/gzip", fg = "#ffb4ab" },
    { mime = "application/x-tar", fg = "#ffb4ab" },
    { mime = "application/x-bzip", fg = "#ffb4ab" },
    { mime = "application/x-bzip2", fg = "#ffb4ab" },
    { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
    { mime = "application/x-rar", fg = "#ffb4ab" },

    # Fallback
    { name = "*", fg = "#8ed5b0", bold = true },
    { name = "*/", fg = "#b4ccbd", bold = true },
  ]
[[plugin.prepend_fetchers]]
  id   = "git"
  name = "*"
  run  = "git"

[[plugin.prepend_fetchers]]
  id   = "git"
  name = "*/"
  run  = "git"
  # : ]]]
