# : Manager [[[

[mgr]
  cwd = { fg = "#ede0d4" }

  # Tab
  tab_active   = { fg = "#452b00", bg = "#f5bd6f", bold = true }
  tab_inactive = { fg = "#ffddb3", bg = "#291800" }
  tab_width    = 1

  # Find
  find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
  find_position = { fg = "#ffb4ab", bold = true, italic = true }

  # Marker
  marker_copied   = { fg = "#a3d26d", bg = "#a3d26d" }
  marker_cut      = { fg = "#d4eabb", bg = "#d4eabb" }
  marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
  marker_selected = { fg = "#b8cda1", bg = "#b8cda1" }

  # Count
  count_copied   = { fg = "#102003", bg = "#d4eabb" }
  count_cut      = { fg = "#102003", bg = "#d4eabb" }
  count_selected = { fg = "#452b00", bg = "#b8cda1" }

  # Border
  border_symbol = "│"
  border_style  = { fg = "#f5bd6f" }

  # : ]]]


  # : Status [[[

[status]
  separator_open  = "🭁"
  separator_close = "🭠"
  separator_style = { bg = "#452b00", fg = "#f5bd6f" }

[mode]
  # Mode
  normal_main = { bg = "#f5bd6f", fg = "#452b00", bold = true }
  normal_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

  # Select mode
  select_main = { bg = "#ddc2a1", fg = "#3e2d16", bold = true }
  select_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

  # Unset mode
  unset_main = { bg = "#b8cda1", fg = "#253515", bold = true }
  unset_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

  # Progress
  progress_label  = { bold = true }
  progress_normal = { fg = "#f5bd6f", bg = "#3f3830" }
  progress_error  = { fg = "#ffb4ab", bg = "#3f3830" }

  # Permissions
  permissions_t = { fg = "#a8783d" }
  permissions_w = { fg = "#6c8b4a" }
  permissions_x = { fg = "#ff2b12" }
  permissions_r = { fg = "#8ac646" }
  permissions_s = { fg = "#ff991a" }

  # : ]]]


  # : Select [[[

[select]
  border   = { fg = "#f5bd6f" }
  active   = { fg = "#b8cda1", bold = true }
  inactive = {}

  # : ]]]


  # : Input [[[

[input]
  border = { fg = "#f5bd6f" }
  value  = { fg = "#ede0d4" }

  # : ]]]


  # : Completion [[[

[completion]
  border = { fg = "#f5bd6f", bg = "#452b00" }

  # : ]]]


  # : Tasks [[[

[tasks]
  border  = { fg = "#f5bd6f" }
  title   = {}
  hovered = { fg = "#d4eabb", underline = true }

  # : ]]]


  # : Which [[[

[which]
  cols            = 3
  mask            = { bg = "#3f3830" }
  cand            = { fg = "#f5bd6f" }
  rest            = { fg = "#452b00" }
  desc            = { fg = "#ede0d4" }
  separator       = " ▶ "
  separator_style = { fg = "#ede0d4" }

  # : ]]]


  # : Help [[[

[help]
  on     = { fg = "#ede0d4" }
  run    = { fg = "#ede0d4" }
  footer = { fg = "#3e2d16", bg = "#ddc2a1" }

  # : ]]]


  # : Notify [[[

[notify]
  title_info  = { fg = "#b8cda1" }
  title_warn  = { fg = "#f5bd6f" }
  title_error = { fg = "#ffb4ab" }

  # : ]]]


  # : File-specific styles [[[

[filetype]
  rules = [
    # Images
    { mime = "image/*", fg = "#ddc2a1" },

    # Videos
    { mime = "video/*", fg = "#b8cda1" },
    { mime = "audio/*", fg = "#b8cda1" },

    # Archives
    { mime = "application/zip", fg = "#ffb4ab" },
    { mime = "application/gzip", fg = "#ffb4ab" },
    { mime = "application/x-tar", fg = "#ffb4ab" },
    { mime = "application/x-bzip", fg = "#ffb4ab" },
    { mime = "application/x-bzip2", fg = "#ffb4ab" },
    { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
    { mime = "application/x-rar", fg = "#ffb4ab" },

    # Fallback
    { name = "*", fg = "#f5bd6f", bold = true },
    { name = "*/", fg = "#ddc2a1", bold = true },
  ]
[[plugin.prepend_fetchers]]
  id   = "git"
  name = "*"
  run  = "git"

[[plugin.prepend_fetchers]]
  id   = "git"
  name = "*/"
  run  = "git"
  # : ]]]
