[manager]
show_hidden = true

[opener]
code = [
    { run = 'nvim "$@"', desc = "Code" }
]
edit = [
	{ run = 'nvim "$@"', block = true }
]

[open]
rules = [
	{ name = "*.json", use = "code" },
	{ name = "*.html", use = "code" },
	{ name = "*.css", use = "code" },
	{ name = "*.toml", use = "code" },
	{ name = "*.txt", use = "edit" },
	{ name = "*.yml", use = "edit" },
]
