set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'

# ------------
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Better colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

set -sg escape-time 50

# Large scrollback
set -g history-limit 100000

# Vim keys in copy mode
setw -g mode-keys vi


# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane splitting
bind | split-window -h
bind - split-window -v

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Enable mouse
set -g mouse on

# Start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Easier window switching
bind -n M-h previous-window
bind -n M-l next-window

# Help menu
bind ? display-popup -E -w 80% -h 60% "tmux list-keys | fzf --reverse --prompt='Binding: '"
bind g display-popup -E -w 80% -h 80% -d "#{pane_current_path}" "lazygit"
bind e display-popup -E -w 80% -h 80% -d "#{pane_current_path}" "spf"
bind o display-popup -E -w 30% -h 50% "~/.config/scripts/open-repo-session.sh \$(sh ~/.config/scripts/list-repos.sh | fzf --reverse --prompt='Repository: ')"

# Reorder windows
bind -r > swap-window -d -t +1
bind -r < swap-window -d -t -1

# ------------------------------
# Everforest dark, hard
bg_dim="#1e2326"
bg0="#272e33"
bg1="#2e383c"
bg2="#374145"
bg3="#414b50"
bg4="#495156"
bg5="#4f5b58"

fg="#d3c6aa"
red="#e67e80"
orange="#e69875"
yellow="#dbbc7f"
green="#a7c080"
aqua="#83c092"
blue="#7fbbb3"
purple="#d699b6"

grey0="#7a8478"
grey1="#859289"
grey2="#9da9a0"

set -g status-position top
set -g status-left-length 60
set -g status-style "fg=${grey1},bg=${bg0}"
set -g status-left " #[fg=${aqua},bold] #S #[fg=${bg3}]│ "
set -g status-right ""

set -g window-status-current-format "#[fg=${yellow},bold][#I] #W #[fg=${grey1}]"
set -g window-status-format "#[fg=${grey1}]#I-#W #[fg=${grey1}]"

set -g message-style "fg=${fg},bg=${bg2}"
set -g mode-style "fg=${bg_dim},bg=${blue}"

set -g pane-border-style "fg=${grey1}"
set -g pane-active-border-style "fg=${fg}"
set -g pane-border-lines single
